model:
  bert_config:
    pretrained_model_name_or_path: "bert-base-uncased"
  optimizer_params:
    lr: 0.001
  freeze_lm: True
tokenizer:
  pretrained_path: "bert-base-uncased"
dataloader_params:
  batch_size: 16
  num_workers: 16
trainer_params:
  accelerator: "gpu"
  max_epochs: 100
  accumulate_grad_batches: 4
  log_every_n_steps: 10
data:
  csv_path: "dataset/ingredients_tags.csv"
  ingredients_index: -1
  test_size: 0.1
  num_examples_to_use_for_training: -1
  tags_to_use:
   - 'pork'
   - 'nuts-grains'
   - 'meat'
   - 'gluten'
   - 'fish'
   - 'dairy'
   - 'seafood'
   - 'restrict diet'
   - 'egg'
   - 'shrimp'