model:
  model_config:
    pretrained_model_name_or_path: "roberta-base"
  optimizer: "adam"
  optimizer_params:
    lr: 0.00005
  # learning_rate_scheduler_params:
  #   num_cycles: 4
  #   num_warmup_steps: 500
  #   num_training_steps: 250000
  #   last_epoch: -1
  freeze_lm: False
  # pos_classes_weight: True
tokenizer:
  pretrained_path: "roberta-base"
dataloader_params:
  batch_size: 2
  num_workers: 16
trainer_params:
  accelerator: "gpu"
  max_steps: 250000
  accumulate_grad_batches: 16
  log_every_n_steps: 10
  # val_check_interval: 0.25
data:
  csv_path: "dataset/ingredients_tags.csv"
  ingredients_column_name: 'ingredients'
  test_size: 0.1
  num_examples_to_use_for_training: 50000
  tags_to_use:
    - "plant-based"
    - "sweet"
    - "seafood"
    - "meat"
    # - "low-sodium"
    - "low-carb"
    # - "healthy"
    # - "low-cholesterol"
    - "low-calorie"
    # - "low-protein"
    # - "low-saturated-fat"
    - "low-fat"
    - "dairy"
    - "nuts"
    # - "diabetic"
    # - "kosher"
    # - "restricted_diet"
use_wandb_logger: True